name: Update Readme

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Adjust Readme
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: python Generator/readme.py

    - name: Remove PythonDataGen
      run: |
        rm -rf PyProfileDataGen 
        rm -rf requirements.txt

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff-index --quiet HEAD || git commit -m "Updated Python data" --allow-empty

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.TOKEN }}
        branch: main